site_name: Céu v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home:            index.md
- Introduction:    010-introduction.md
- Lexical Rules:   020-lexical_rules.md
- Types:           030-types.md
- Storage Classes: 040-storage_classes.md
- Statements:      050-statements.md
- Expressions:     060-expressions.md
- Static Checks:   070-static_checks.md
- Environment:     080-environment.md
- Errors:          090-errors.md
- Syntax:          syntax.md
- License:         license.md
